# Generated by Django 4.0.1 on 2022-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latlongapp', '0002_remove_local_iso2_remove_local_iso3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='area',
            field=models.FloatField(),
        ),
    ]
